// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-wUEhhVcLzRJmRMN3yIAJCUuZd5M4XU',
    appId: '1:628604743496:web:5c52c582962e4e57714d7d',
    messagingSenderId: '628604743496',
    projectId: 'mochi-clicker',
    authDomain: 'mochi-clicker.firebaseapp.com',
    storageBucket: 'mochi-clicker.appspot.com',
    measurementId: 'G-FYCGRBT0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqSwgxQYVImlsypARZ22Hwn_rJaoUG0c',
    appId: '1:628604743496:android:b8ae5084bb943e8b714d7d',
    messagingSenderId: '628604743496',
    projectId: 'mochi-clicker',
    storageBucket: 'mochi-clicker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQw6CYLid5T9jaBrreKU7SvuecumveCw',
    appId: '1:628604743496:ios:5bc62071757a8400714d7d',
    messagingSenderId: '628604743496',
    projectId: 'mochi-clicker',
    storageBucket: 'mochi-clicker.appspot.com',
    iosClientId: '628604743496-54frnvlk5hugucol0raqbro3nrsja7kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeQw6CYLid5T9jaBrreKU7SvuecumveCw',
    appId: '1:628604743496:ios:5bc62071757a8400714d7d',
    messagingSenderId: '628604743496',
    projectId: 'mochi-clicker',
    storageBucket: 'mochi-clicker.appspot.com',
    iosClientId: '628604743496-54frnvlk5hugucol0raqbro3nrsja7kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );
}
